version: '3'
services:
  jenkins:
    build:
      context: jenkins-docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
volumes:
  jenkins-data: